### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by oviniciuslara** [1p6/VideoCall#1]
How can I make it work? I'm kind of confused about it

**Comment by 1p6** [comment]
I originally wanted to make it work like [this](https://github.com/cjb/serverless-webrtc/), but after I read some examples for webrtc I determined that you need to send ice candidates for video streaming which would make sending all the information alot harder.  After figuring this out I just went on to make a [simpler application](https://github.com/1p6/Coop-Textbox) which only needs to send data, not video.  I did however come up with a way to do this that might actually work.  It goes like this:  Setup a data connection like both repos mentioned and then use that data connection to setup another connection to stream the video and audio.

If you would like to try to implement this yourself then the repos above and these html5rocks articles are a good place to start.

http://www.html5rocks.com/en/tutorials/webrtc/basics/
http://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

**Comment by 1p6** [comment]
I actually just got this to work using said method above.  This repo should now work.
